#!/bin/sh -e

export PKG_CONFIG_ALLOW_CROSS=1
export PKG_CONFIG_ALL_STATIC=1
export PKG_CONFIG_PATH=/usr/lib/pkgconfig

cargo build \
  --release \
  --workspace \
  --verbose

mkdir -pv "$1/bin"

find target/release/ -type f -name 'nu*' -exec cp -av {} "$1/bin/" +
